apiVersion: v1
kind: Service
metadata:
  name: auth-api-service
spec:
  selector:
    app: auth-api-pods
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api-pods
  template:
    metadata:
      labels:
        app: auth-api-pods
    spec:
      containers:
      - name: auth-api-container
        image: rwijupal3058/auth-api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
          - name: TOKEN_KEY
            value: 'shouldbeverysecure'

