apiVersion: v1
kind: Service
metadata:
  name: tasks-api-service
spec:
  selector:
    app: tasks-api-pods
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks-api-pods
  template:
    metadata:
      labels:
        app: tasks-api-pods
    spec:
      containers:
      - name: tasks-api-container
        image: rwijupal3058/tasks-api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_CONNECTION_URI
          value: "mongodb+srv://rwijupal:SALTlake3058@cluster0.bcpw2e8.mongodb.net/?retryWrites=true&w=majority"
        - name: AUTH_API_ADDRESS
          value: 'auth-api-service.default:8000'