---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: users-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /app/users
    type: DirectoryOrCreate 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Service
metadata:
  name: users-api-service
spec:
  selector:
    app: users-api-pods
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api-pods
  template:
    metadata:
      labels:
        app: users-api-pods
    spec:
      containers:
        - name: users-api-container
          ports:
          - containerPort: 3000
          image: rwijupal3058/users-api:latest
          env:
            - name: MONGODB_CONNECTION_URI
              value: "mongodb+srv://rwijupal:SALTlake3058@cluster0.bcpw2e8.mongodb.net/?retryWrites=true&w=majority"
            - name: AUTH_API_ADDRESS
              value: 'auth-api-service.default:8000'
          volumeMounts:
            - mountPath: /app/users
              name: users-logs
      volumes:
        - name: users-logs
          persistentVolumeClaim:
            claimName: users-pvc